=== euroargodev/argo-metadata-validator/tests/files/user_defined/schema/sensor.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "./sensor.schema.json",
    "title": "JSON Schema for sensors",
    "description": "A JSON Schema used to attribute calibration information to parameter and sensor metadata elements. This is a copy of the Argo metadata format Version 3.41.1",
    "format_version": { "const": "0.4.0" },
    "type": "object",
    "properties": {
        "sensor_info": {
            "type": "object",
            "properties": {
                "created_by": {
                    "type": "string"
                },
                "date_creation": {
                    "type": "string",
                    "format": "date-time"
                },
                "link": {
                    "const" : "./sensor.schema.json"
                },
                "format_version": {
                    "$ref": "#/format_version"
                },
                "contents": {
                    "type": "string"
                },
                "sensor_described": {
                    "type": "string"
                }
            },
            "required": [
                "created_by",
                "date_creation",
                "link",
                "format_version",
                "contents",
                "sensor_described"
            ]
        },
        "@context": {
            "type": "object",
            "properties": {
                "SDN:P01::": { "const": "http://vocab.nerc.ac.uk/collection/P01/current/" },
                "SDN:L05::": { "const": "http://vocab.nerc.ac.uk/collection/L05/current/" },
                "SDN:L35::": { "const": "http://vocab.nerc.ac.uk/collection/L35/current/" },
                "SDN:L22::": { "const": "http://vocab.nerc.ac.uk/collection/L22/current/" }
            },
            "required": [
                "SDN:P01::",
                "SDN:L05::",
                "SDN:L35::",
                "SDN:L22::"
            ],
            "additionalProperties": false
        },
        "SENSORS": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "SENSOR": {
                        "type" : "string",
                        "format" : "uri",
                        "pattern" : "^SDN:L05::",
                        "description": "SENSOR string must be valid in current NVS reference table L05",
                        "validation-uri" : "https://vocab.nerc.ac.uk/collection/L05/current/"
                    },
                    "SENSOR_MAKER": {
                        "type" : "string",
                        "format" : "uri",
                        "pattern" : "^SDN:L35::",
                        "description": "SENSOR_MAKER string must be valid in current NVS reference table L35",
                        "validation-uri": "https://vocab.nerc.ac.uk/collection/L35/current/"
                    },
                    "SENSOR_MODEL": {
                        "type" : "string",
                        "format" : "uri",
                        "pattern" : "^SDN:L22::",
                        "description": "SENSOR_MODEL string must be valid in current NVS reference table L22",
                        "validation-uri": "https://vocab.nerc.ac.uk/collection/L22/current/"
                    },
                    "SENSOR_MODEL_FIRMWARE": {
                        "type": "string",
                        "description": "Firmware version of this sensor_model, defined by the sensor_maker"
                    },
                    "SENSOR_SERIAL_NO": {
                        "type": "string",
                        "description": "Serial number of the sensor"
                    },
                    "sensor_vendorinfo": {
                        "$ref" : "./vendors.schema.json#/$defs/sensor_vendorinfo"                        
                    }
                },
                "required": [
                    "SENSOR",
                    "SENSOR_MAKER",
                    "SENSOR_MODEL",
                    "SENSOR_SERIAL_NO",
                    "SENSOR_MODEL_FIRMWARE"
                ],
                "additionalProperties": false
            },
            "minItems": 1,
            "uniqueItems": true
        },
        "PARAMETERS": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "PARAMETER": {
                        "type" : "string",
                        "format" : "uri",
                        "pattern" : "^SDN:P01::",
                        "description": "PARAMETER string must be valid in current NVS reference table P01",
                        "validation_uri": "http://vocab.nerc.ac.uk/collection/P01/current/"
                    },
                    "PARAMETER_SENSOR": {
                        "type" : "string",
                        "format" : "uri",
                        "pattern" : "^SDN:L05::",
                        "description": "PARAMETER_SENSOR string must be valid in current NVS reference table L05 and must be listed as a SENSOR in the SENSORS section above",
                        "validation_uri": "http://vocab.nerc.ac.uk/collection/L05/current/"
                    },
                    "PARAMETER_UNITS": {
                        "type": "string"
                    },
                    "PARAMETER_ACCURACY": {
                        "type": "string"
                    },
                    "PARAMETER_RESOLUTION": {
                        "type": "string"
                    },
                    "PREDEPLOYMENT_CALIB_EQUATION": {
                        "type": "string",
                        "description" : "Calibration equation for this parameter."
                    },
                    "PREDEPLOYMENT_CALIB_COEFFICIENT_LIST": {
                        "type": "object",
                        "description" : "Calibation coefficients are listed individually here, string-encoded to guarantee precision.  They are compiled to create the PREDEPLOYMENT_CALIB_COEFFCIENT string"
                    },
                    "PREDEPLOYMENT_CALIB_COMMENT": {
                        "type": "string"
                    },
                    "PREDEPLOYMENT_CALIB_DATE": {
                        "anyOf": [
                            {
                                "type": "string",
                                "format": "date-time"
                            },
                            {
                                "type": "string",
                                "const": " "
                            }
                        ]
                    },
                    "parameter_vendorinfo": {
                        "$ref" : "./vendors.schema.json#/$defs/parameter_vendorinfo"
                    },
                    "predeployment_vendorinfo": {
                        "$ref" : "./vendors.schema.json#/$defs/predeployment_vendorinfo"
                    }
                },
                "required": [
                    "PARAMETER",
                    "PARAMETER_SENSOR",
                    "PARAMETER_UNITS",
                    "PARAMETER_ACCURACY",
                    "PARAMETER_RESOLUTION",
                    "PREDEPLOYMENT_CALIB_EQUATION",
                    "PREDEPLOYMENT_CALIB_COEFFICIENT_LIST",
                    "PREDEPLOYMENT_CALIB_COMMENT",
                    "PREDEPLOYMENT_CALIB_DATE"
                ],
                "additionalProperties": false
            },
            "minItems": 1,
            "uniqueItems": true
        },
        "instrument_vendorinfo": {
            "$ref" : "./vendors.schema.json#/$defs/instrument_vendorinfo"
        }
    },
    "required": [
        "@context",
        "sensor_info",
        "SENSORS",
        "PARAMETERS"
    ],
    "uniqueItems": true,
    "additionalProperties": false

}

=== euroargodev/argo-metadata-validator/tests/files/user_defined/valid_sensor.json
{
    "sensor_info": {
      "created_by": "johert",
      "date_creation": "2025-12-23T14:00:00Z",
      "link" : "./sensor.schema.json",
      "format_version": "0.4.0",
      "contents": "json file to describe a sensor v0.4.0 draft",
      "sensor_described": "AANDERAA-TOOL1239-421"
    },
    "@context": {
      "SDN:P01::": "http://vocab.nerc.ac.uk/collection/P01/current/",
      "SDN:L05::": "http://vocab.nerc.ac.uk/collection/L05/current/",
      "SDN:L35::": "http://vocab.nerc.ac.uk/collection/L35/current/",
      "SDN:L22::": "http://vocab.nerc.ac.uk/collection/L22/current/"
    },
  "SENSORS": [
      {
        "SENSOR": "SDN:L05::351",
        "SENSOR_MAKER": "SDN:L35::MAN0007",
        "SENSOR_MODEL": "SDN:L22::TOOL1239",
        "SENSOR_MODEL_FIRMWARE": " ",
        "SENSOR_SERIAL_NO": "421"
      }
    ],
    "PARAMETERS": [
      {
        "PARAMETER": "SDN:P01::DOXYAAOP",
        "PARAMETER_SENSOR": "SDN:L05::351",
        "PARAMETER_UNITS": "degree",
        "PARAMETER_ACCURACY": " ",
        "PARAMETER_RESOLUTION": " ",
        "PREDEPLOYMENT_CALIB_EQUATION": "none",
        "PREDEPLOYMENT_CALIB_COEFFICIENT_LIST": {  },
        "PREDEPLOYMENT_CALIB_COMMENT": "Phase measurement with blue excitation light; see TD269 Operating manual oxygen optode 4330, 4835, 483",
        "PREDEPLOYMENT_CALIB_DATE": " "
      },
      {
        "PARAMETER": "SDN:P01::OXYCOPVB",
        "PARAMETER_SENSOR": "SDN:L05::351",
        "PARAMETER_UNITS": "degree",
        "PARAMETER_ACCURACY": " ",
        "PARAMETER_RESOLUTION": " ",
        "PREDEPLOYMENT_CALIB_EQUATION": "none",
        "PREDEPLOYMENT_CALIB_COEFFICIENT_LIST": { },
        "PREDEPLOYMENT_CALIB_COMMENT": "Phase measurement with red excitation light; see TD269 Operating manual oxygen optode 4330, 4835, 4831",
        "PREDEPLOYMENT_CALIB_DATE": " "    
      },
      {
        "PARAMETER": "SDN:P01::OXYCOPVR",
        "PARAMETER_SENSOR": "SDN:L05::351",
        "PARAMETER_UNITS": "degC",
        "PARAMETER_ACCURACY": "0.03",
        "PARAMETER_RESOLUTION": "0.01",
        "PREDEPLOYMENT_CALIB_EQUATION": "TEMP_DOXY=T0+T1*TEMP_VOLTAGE_DOXY+T2*TEMP_VOLTAGE_DOXY^2+T3*TEMP_VOLTAGE_DOXY^3+T4*TEMP_VOLTAGE_DOXY^4+T5*TEMP_VOLTAGE_DOXY^5; with TEMP_VOLTAGE_DOXY=voltage from thermistor bridge (mV)",
        "PREDEPLOYMENT_CALIB_COEFFICIENT_LIST": {
          "T0": "1",
          "T1": "2",
          "T2": "3",
          "T3": "4",
          "T4": "5",
          "T5": "6"
        },
        "PREDEPLOYMENT_CALIB_COMMENT": "optode temperature, see TD269 Operating manual oxygen optode 4330, 4835, 4831",
        "PREDEPLOYMENT_CALIB_DATE": "2020-01-01T00:00:00Z"
      },
      {
        "PARAMETER": "SDN:P01::OXYCPHAB",
        "PARAMETER_SENSOR": "SDN:L05::351",
        "PARAMETER_UNITS": "umol/kg",
        "PARAMETER_ACCURACY": "8 umol/kg or 10%",
        "PARAMETER_RESOLUTION": "1 umol/kg",
        "PREDEPLOYMENT_CALIB_EQUATION": "TPHASE_DOXY=C1PHASE_DOXY-C2PHASE_DOXY; Phase_Pcorr=TPHASE_DOXY+Pcoef1*PRES/1000; CalPhase=PhaseCoef0+PhaseCoef1*Phase_Pcorr+PhaseCoef2*Phase_Pcorr^2+PhaseCoef3*Phase_Pcorr^3; MOLAR_DOXY=[((c3+c4*TEMP_DOXY)/(c5+c6*CalPhase))-1]/Ksv; Ksv=c0+c1*TEMP_DOXY+c2*TEMP_DOXY^2; O2=MOLAR_DOXY*Scorr*Pcorr; Scorr=A*exp[PSAL*(B0+B1*Ts+B2*Ts^2+B3*Ts^3)+C0*PSAL^2]; A=[(1013.25-pH2O(TEMP,Spreset))/(1013.25-pH2O(TEMP,PSAL))]; pH2O(TEMP,S)=1013.25*exp[D0+D1*(100/(TEMP+273.15))+D2*ln((TEMP+273.15)/100)+D3*S]; Pcorr=1+((Pcoef2*TEMP+Pcoef3)*PRES)/1000; Ts=ln[(298.15-TEMP)/(273.15+TEMP)]; DOXY=O2/rho, where rho is the potential density [kg/L] calculated from CTD data",
        "PREDEPLOYMENT_CALIB_COEFFICIENT_LIST": {
          "Spreset": "0",
          "Pcoef1": "0.1",
          "Pcoef2": "0.00022",
          "Pcoef3": "0.0419",
          "B0": "0.00624523",
          "B1": "-0.00737614",
          "B2": "-0.010341",
          "B3": "-0.00817083",
          "C0": "3.1201642E-3",
          "PhaseCoef0": "-1.652",
          "PhaseCoef1": "1",
          "PhaseCoef2": "0",
          "PhaseCoef3": "0",
          "c0": "0.00261275",
          "c1": "0.00011268",
          "c2": "2.2309e-06",
          "c3": "200.183",
          "c4": "-0.223497",
          "c5": "-43.6776",
          "c6": "4.10578",
          "D0": "24.4543",
          "D1": "-67.4509",
          "D2": "-4.8489",
          "D3": "-0.000544",
          "C1": "-285.56594E-6",
          "C2": "316.32993E-9",
          "C3": "-1.0767272E-6"
        },
        "PREDEPLOYMENT_CALIB_COMMENT": "see TD269 Operating manual oxygen optode 4330, 4835, 4831; see Processing Argo OXYGEN data at the DAC level, Version 2.2 (DOI: http://dx.doi.org/10.13155/39795)",
        "PREDEPLOYMENT_CALIB_DATE": "2020-01-01T00:00:00Z",
        "parameter_vendorinfo": {
          "example": "Vendors can add their own parameter info here; they can add any field they like as a fieldname below parameter_vendorinfo"
        },
        "predeployment_vendorinfo": {
          "example": "Vendors can add their own predeployment info here; they can add any field they like as a fieldname below predeployment_vendorinfo"
        }
      },
      {
        "PARAMETER": "SDN:P01::OXYCPHAC",
        "PARAMETER_SENSOR": "SDN:L05::351",
        "PARAMETER_UNITS": "mbar",
        "PARAMETER_ACCURACY": " ",
        "PARAMETER_RESOLUTION": " ",
        "PREDEPLOYMENT_CALIB_EQUATION": "TPHASE_DOXY=C1PHASE_DOXY-C2PHASE_DOXY; Phase_Pcorr=TPHASE_DOXY+Pcoef1*PRES/1000; CalPhase=PhaseCoef0+PhaseCoef1*Phase_Pcorr+PhaseCoef2*Phase_Pcorr^2+PhaseCoef3*Phase_Pcorr^3; Ksv=c0+c1*TEMP_DOXY+c2*TEMP_DOXY^2; MOLAR_DOXY=[((c3+c4*TEMP_DOXY)/(c5+c6*CalPhase))-1]/Ksv; Pcorr=1+((Pcoef2*TEMP+Pcoef3)*PRES)/1000; MOLAR_DOXY=MOLAR_DOXY*Pcorr; pH2Osat=1013.25*exp[D0+D1*(100/(TEMP+273.15))+D2*ln((TEMP+273.15)/100)]; Tcorr=44.6596*exp[2.00907+3.22014*Ts+4.05010*Ts^2+4.94457*Ts^3-2.56847e-1*Ts^4+3.88767*Ts^5]; Ts=ln[(298.15-TEMP)/(273.15+TEMP)]; PPOX_DOXY=MOLAR_DOXY*(0.20946*(1013.25-pH2Osat))/Tcorr*exp[0.317*PRES/(8.314*(TEMP+273.15))]",
        "PREDEPLOYMENT_CALIB_COEFFICIENT_LIST": {
          "Pcoef1": "0.1",
          "Pcoef2": "0.00022",
          "Pcoef3": "0.0419",
          "PhaseCoef0": "-1.652",
          "PhaseCoef1": "1",
          "PhaseCoef2": "0",
          "PhaseCoef3": "0",
          "c0": "0.00261275",
          "c1": "0.00011268",
          "c2": "2.2309e-06",
          "c3": "200.183",
          "c4": "-0.223497",
          "c5": "-43.6776",
          "c6": "4.10578",
          "D0": "24.4543",
          "D1": "-67.4509",
          "D2": "-4.8489",
          "C0": "3.1201642E-3",
          "C1": "-285.56594E-6",
          "C2": "316.32993E-9",
          "C3": "-1.0767272E-6"
        },
        "PREDEPLOYMENT_CALIB_COMMENT": "see TD269 Operating manual oxygen optode 4330, 4835, 4831; see Processing Argo OXYGEN data at the DAC level, Version 2.2 (DOI: http://dx.doi.org/10.13155/39795)",
        "PREDEPLOYMENT_CALIB_DATE": "2020-01-01T00:00:00Z",
        "parameter_vendorinfo": {
          "example": "Vendors can add their own parameter info here; they can add any field they like as a fieldname below parameter_vendorinfo"
        },
        "predeployment_vendorinfo": {
          "example": "Vendors can add their own predeployment info here; they can add any field they like as a fieldname below predeployment_vendorinfo"
        }
      }
    ],
    "instrument_vendorinfo": {
      "example": "Vendors can add something about the whole instrument here; they can add field they like as a fieldname below instrument_vendorinfo"
    }
  }
